support TLS
hlb8122/tracing-gelf pull request #12
Opened 2021-08-05 14:02 UTC by glebpom

2021-08-05 16:52 UTC, hlb8122 commented
Thank you kindly, I will try look over this properly during the weekend.

2021-08-13 10:25 UTC, hlb8122 requested changes
If you'd rather sit back and chill, I can try get this done if I find some time.

2021-08-13 10:25 UTC, hlb8122 commented on Cargo.toml
> +futures-util = { version = "0.3", features = ["sink", "io"] }
Can add a dedicated feature flag for these additional dependency features and the `tokio-rustls` import?

2021-08-13 10:25 UTC, hlb8122 commented on Cargo.toml
> +futures-util = { version = "0.3", features = ["sink", "io"] }
Perhaps we can keep close to the `features` decisions made by `reqwest` and call the feature flag `rustls-tls`.

https://github.com/seanmonstar/reqwest/blob/master/Cargo.toml

2021-08-13 10:25 UTC, hlb8122 commented on src/lib.rs
> +        domain_name: String,
We should take `domain_name` as a `&str` rather than `String` if it's only use is as an argument to `pub fn try_from_ascii_str(dns_name: &str)`

2021-08-13 10:25 UTC, hlb8122 commented on src/lib.rs
> +        let dnsname = tokio_rustls::webpki::DNSNameRef::try_from_ascii_str(&domain_name)
There are a lot of `.to_owned()` and `.clone()` in this function, can we reduce it?

2021-08-13 10:25 UTC, hlb8122 commented on src/lib.rs
> +                        handle_tcp_connection(addr, f.clone(), &mut ok_receiver).await;
Can we pass this by reference instead, rather than cloning?

2021-08-13 10:25 UTC, hlb8122 commented on src/lib.rs
> +    let try_connect = async move {
Why is this in an `async` block?

2021-08-26 20:03 UTC, adeschamps reviewed
I'm also quite interested in seeing this get merged (I had reached out privately to @glebpom to ask about making a PR from the fork they mentioned in #9 -- much appreciated!), so I opened a PR against this PR's branch at https://github.com/glebpom/tracing-gelf/pull/1 and summarized my changes under each of your comments.

2021-08-26 20:03 UTC, adeschamps commented on src/lib.rs
> +                        handle_tcp_connection(addr, f.clone(), &mut ok_receiver).await;
a2c85dc

2021-08-26 20:03 UTC, adeschamps commented on src/lib.rs
> +        let dnsname = tokio_rustls::webpki::DNSNameRef::try_from_ascii_str(&domain_name)
I can't think of a way to avoid this. Ultimately, `dnsname` gets moved into the future that the user of `tracing-gelf` will spawn on their runtime, so I think the future needs to take ownership of it.

2021-08-26 20:03 UTC, adeschamps commented on src/lib.rs
> +        domain_name: String,
261aadd

2021-08-26 20:03 UTC, adeschamps commented on src/lib.rs
> +    let try_connect = async move {
I believe it's to enable the use of `?`, which is used twice in this block. I refactored this in 68961da so the function propagates its errors (I did the same in `handle_udp_connection` for consistency). The callers of these functions still ignore the error, but that's probably a more logical place to handle/log it if someone wants to make another PR.

2021-08-26 20:03 UTC, adeschamps commented on Cargo.toml
> +futures-util = { version = "0.3", features = ["sink", "io"] }
I was able to eliminate these extra features in c56e423 by using `tokio::io::split` instead of the equivalent function provided by `futures-util`.

2021-08-30 15:19 UTC, glebpom commented
@adeschamps Thanks for the PR! I've merged it. Feel free to add more changes or create another PR in this repo based on initially my code. I'm quite busy now and it's not in my focus, so I can be a bit slow

2021-09-13 14:56 UTC, adeschamps commented on src/lib.rs
> +    fn connect_tcp<T>(self, addr: T) -> Result<(Logger, BackgroundTask), BuilderError>
```suggestion
    pub fn connect_tcp<T>(self, addr: T) -> Result<(Logger, BackgroundTask), BuilderError>
```

Looks like this was accidentally made non-pub.

2021-12-07 13:49 UTC, hlb8122 commented
@adeschamps @glademiller Sorry for dropping the ball on this one lads.

I've had a look through today and put some tweaks to it.

https://github.com/glebpom/tracing-gelf/pull/2

If you think that's satisficatory I'll do some house keeping then do a release ASAP.

2021-12-08 14:49 UTC, adeschamps commented
Not a problem! I really appreciate what you're doing. We've been using the branch from this PR, so it hasn't been blocking us.

Those changes in https://github.com/glebpom/tracing-gelf/pull/2 all look good to me.

2021-12-12 22:51 UTC, hlb8122 commented
https://github.com/hlb8122/tracing-gelf/pull/14

2021-12-12 22:51 UTC, closed without merging

2021-12-12 23:36 UTC, hlb8122 commented
This was merged and published in `0.5.2` @adeschamps @glademiller