Upgrade to tracing-subscriber 0.3
hlb8122/tracing-gelf pull request #13
Opened 2021-12-07 15:01 UTC by bertof

Updated the library to use the newer tracing-subscriber traits.
Changed the least amount of code possible and tested checking for regression.
Bumped the library version as the interfaces have changed.

2021-12-07 16:05 UTC, hlb8122 commented
Thanks very much. Aiming for a release sometime this week. Will make sure to include this.

2021-12-07 23:01 UTC, bertof commented
You're welcome! Thank you for this library, it's really easy to use.

2021-12-13 01:50 UTC, hlb8122 requested changes

2021-12-13 01:50 UTC, hlb8122 commented on Cargo.toml
> +version = "0.6.0"
Do you mind reverting this? I'd like to bump to `0.6.0` in a~"prepare for release" commit. I released a patch version recently and this is causing merge conflict.

2021-12-13 01:50 UTC, hlb8122 commented on src/lib.rs
> +            let span = ctx.current_span().id().and_then(|id| {
I did a little jiggle around before `0.6`. Do you mind rebasing against lastest `master`, this should work

```rust
            let span = ctx.current_span().id().and_then(|id| {
                ctx.span_scope(id).map(|scope| {
                    scope.from_root().fold(String::new(), |mut spans, span| {
                        // Add span fields to the base object
                        if let Some(span_object) = span.extensions().get::<HashMap<Cow<'static, str>, Value>>() {
                            object.extend(span_object.clone());
                        }
                        if spans != String::new() {
                            spans = format!("{}:{}", spans, span.name());
                        } else {
                            spans = span.name().to_string();
                        }

                        spans
                    })
                })
            });

            if let Some(span) = span {
                object.insert("_span".into(), span.into());
            }
```

2021-12-13 09:28 UTC, bertof commented
I've updated my PR.

2021-12-13 17:59 UTC, hlb8122 commented
@bertof Thanks

2021-12-14 01:38 UTC, merged

2021-12-14 02:15 UTC, hlb8122 commented
@bertof Released in `0.6` 👍